# Generated by Django 2.0.2 on 2018-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-datePublished', '-title', '-content']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='datePublished',
            field=models.DateField(auto_now=True),
        ),
    ]
