# Generated by Django 2.0.2 on 2018-02-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180228_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datePublished',
            field=models.DateField(auto_now=True, help_text='Date blog published'),
        ),
    ]
