# Generated by Django 2.0.2 on 2018-02-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180228_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['datePublished', '-title', '-content']},
        ),
    ]
