# Generated by Django 2.0.3 on 2018-03-08 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180303_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='datePublished',
            field=models.DateTimeField(auto_now=True, help_text='Date Blog Published'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='op',
            field=models.ForeignKey(help_text='Original Poster', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Blog Description', max_length=256),
        ),
    ]
