# Generated by Django 2.0.3 on 2018-03-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180307_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-datePublished', 'title', 'description', 'content', 'op']},
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default=1, help_text='Blog Description', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Blog Title', max_length=256),
        ),
    ]
